// ─── Central Mock Data ────────────────────────────────────────────────────────
// This file provides fallback data for all components when the API is unavailable.

export const MOCK_DESTINATIONS = [
    {
        _id: '1',
        name: 'Kashmir',
        slug: 'kashmir',
        state: 'Jammu & Kashmir',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800&q=80',
            'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80',
            'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80',
        ],
        shortDescription: 'Paradise on Earth — snow-capped peaks, shikara rides, and blooming gardens.',
        description: 'Kashmir, often called "Paradise on Earth," is a breathtaking destination nestled in the Himalayas. From the serene Dal Lake with its iconic shikara rides to the snow-draped slopes of Gulmarg, every corner tells a story of natural grandeur.',
        basePrice: 18999,
        duration: 7,
        rating: 4.8,
        reviewCount: 2847,
        isFeatured: true,
        category: 'Mountains',
        difficulty: 'Easy',
        tags: ['Mountains', 'Honeymoon', 'Family', 'Adventure'],
        highlights: ['Dal Lake Shikara Ride', 'Gulmarg Gondola', 'Pahalgam Valley', 'Srinagar Old City', 'Mughal Gardens'],
        bestTimeToVisit: 'April to October',
        weather: { summer: '15-25°C', winter: '-5 to 10°C', monsoon: '18-22°C' },
        inclusions: ['Hotel accommodation (4-star)', 'Breakfast & dinner', 'All transfers', 'Shikara ride', 'Airport pickup'],
        exclusions: ['Flight tickets', 'Lunch', 'Personal expenses', 'Travel insurance'],
        itinerary: [
            { day: 1, title: 'Arrival in Srinagar', description: 'Arrive in Srinagar, check into your houseboat on Dal Lake. Evening shikara ride at sunset.', activities: ['Dal Lake Shikara Ride', 'Mughal Garden Visit'] },
            { day: 2, title: 'Gulmarg Excursion', description: 'Drive to Gulmarg, the Meadow of Flowers. Take the famous Gondola cable car ride to Apharwat Peak.', activities: ['Gondola Ride', 'Snow Activities', 'Biking'] },
            { day: 3, title: 'Pahalgam Valley', description: 'Explore the beautiful Pahalgam valley, visit Betaab Valley and Aru Valley.', activities: ['Betaab Valley', 'Aru Valley', 'Lidder River Walk'] },
            { day: 4, title: 'Sonamarg Day Trip', description: 'Visit Sonamarg - Meadow of Gold, enjoy the scenic mountain landscapes.', activities: ['Thajiwas Glacier', 'Horse Ride', 'Sindh River'] },
            { day: 5, title: 'Srinagar City Tour', description: 'Explore Old Srinagar - Shankaracharya Temple, Jama Masjid, Lal Chowk.', activities: ['Shankaracharya Temple', 'Lal Chowk', 'Local Markets'] },
            { day: 6, title: 'Additional Excursion', description: 'Free day for shopping or optional Doodhpathri excursion.', activities: ['Doodhpathri', 'Local Shopping', 'Cuisine Tour'] },
            { day: 7, title: 'Departure', description: 'Check out and transfer to airport. Carry memories of paradise.', activities: ['Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'a1', name: 'Gondola Cable Car Ride', price: 2500, duration: '3 hrs', description: 'World\'s second-highest cable car with stunning Himalayan views' },
            { id: 'a2', name: 'Houseboat Upgrade', price: 3500, duration: '1 night', description: 'Stay in a luxury heritage houseboat on Dal Lake' },
            { id: 'a3', name: 'Skiing Package', price: 4000, duration: '1 day', description: 'Professional skiing with equipment and instructor at Gulmarg' },
            { id: 'a4', name: 'ATV Ride Pahalgam', price: 1800, duration: '2 hrs', description: 'Off-road ATV adventure through mountain trails' },
        ],
        faqs: [
            { q: 'What is the best time to visit Kashmir?', a: 'April to October is ideal. For snow, visit December to February.' },
            { q: 'Is Kashmir safe to visit?', a: 'Tourist areas are generally safe. We arrange all logistics with trusted local partners.' },
            { q: 'Do I need permits?', a: 'Indian nationals don\'t need permits. Foreign nationals need Protected Area Permits for certain zones.' },
        ],
    },
    {
        _id: '2',
        name: 'Goa',
        slug: 'goa',
        state: 'Goa',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&q=80',
            'https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=80',
        ],
        shortDescription: 'Sun, sand, and sea — India\'s beach paradise with vibrant nightlife.',
        description: 'Goa is India\'s smallest state with the biggest heart. Famous for pristine beaches, Portuguese heritage, vibrant nightlife, and delicious seafood, Goa offers an experience that keeps travelers coming back for more.',
        basePrice: 12999,
        duration: 5,
        rating: 4.7,
        reviewCount: 5234,
        isFeatured: true,
        category: 'Beach',
        difficulty: 'Easy',
        tags: ['Beach', 'Honeymoon', 'Adventure', 'Family'],
        highlights: ['North Goa Beaches', 'Old Goa Churches', 'Dudhsagar Falls', 'Nightlife', 'Water Sports'],
        bestTimeToVisit: 'November to February',
        weather: { summer: '28-35°C', winter: '22-30°C', monsoon: '25-30°C' },
        inclusions: ['Hotel accommodation (3-star beachside)', 'Breakfast', 'Airport transfers', 'Beach tour', 'Dudhsagar trip'],
        exclusions: ['Flight tickets', 'Lunch & Dinner', 'Water sports', 'Personal expenses'],
        itinerary: [
            { day: 1, title: 'Arrival & North Goa Beaches', description: 'Arrive in Goa airport, check-in. Explore Calangute, Baga, and Anjuna beaches.', activities: ['Beach Exploration', 'Sunset at Vagator'] },
            { day: 2, title: 'Old Goa Heritage Tour', description: 'Visit UNESCO World Heritage churches, Basilica of Bom Jesus, Fort Aguada.', activities: ['Basilica of Bom Jesus', 'Fort Aguada', 'Spice Plantation Tour'] },
            { day: 3, title: 'Dudhsagar Falls Adventure', description: 'Full-day trip to majestic Dudhsagar waterfall by jeep safari through forests.', activities: ['Dudhsagar Waterfall', 'Jungle Safari', 'Swimming'] },
            { day: 4, title: 'Water Sports & South Goa', description: 'Morning water sports, afternoon explore serene South Goa beaches.', activities: ['Jet Ski', 'Parasailing', 'Palolem Beach', 'Banana Boat'] },
            { day: 5, title: 'Departure', description: 'Last morning shopping at Mapusa market, then airport transfer.', activities: ['Mapusa Market Shopping', 'Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'b1', name: 'Water Sports Package', price: 2000, duration: '3 hrs', description: 'Jet ski, parasailing, banana boat, and more' },
            { id: 'b2', name: 'Scuba Diving', price: 3500, duration: '4 hrs', description: 'Beginner scuba dive with certified instructor at Grande Island' },
            { id: 'b3', name: 'Sunset Cruise', price: 1500, duration: '2 hrs', description: 'Romantic sunset cruise with dinner on the Mandovi River' },
            { id: 'b4', name: 'Casino Night', price: 2500, duration: 'Evening', description: 'Premium casino experience on Goa\'s famous floating casino' },
        ],
        faqs: [
            { q: 'When is the best time to visit Goa?', a: 'November to February is perfect — pleasant weather, blue skies, and festive atmosphere.' },
            { q: 'Is Goa suitable for families?', a: 'Absolutely! South Goa beaches are calm and family-friendly. North Goa is more lively.' },
        ],
    },
    {
        _id: '3',
        name: 'Kerala',
        slug: 'kerala',
        state: 'Kerala',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1580974852861-c381510bc98a?w=800&q=80',
            'https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&q=80',
        ],
        shortDescription: 'God\'s Own Country — lush backwaters, misty hills, and Ayurveda.',
        description: 'Kerala is a state of incredible diversity — from the lush green hills of Munnar to the tranquil backwaters of Alleppey, from pristine beaches to ancient temples. Experience Ayurvedic wellness, elephant sanctuaries, and world-class cuisine.',
        basePrice: 16999,
        duration: 6,
        rating: 4.9,
        reviewCount: 3421,
        isFeatured: true,
        category: 'Heritage',
        difficulty: 'Easy',
        tags: ['Heritage', 'Honeymoon', 'Family', 'Mountains'],
        highlights: ['Alleppey Backwaters', 'Munnar Tea Gardens', 'Periyar Wildlife', 'Kovalam Beach', 'Kathakali Show'],
        bestTimeToVisit: 'September to March',
        weather: { summer: '28-35°C', winter: '20-28°C', monsoon: '22-30°C' },
        inclusions: ['Houseboat stay (1 night)', 'Resort accommodation', 'Breakfast & dinner', 'All transfers', 'Kathakali show'],
        exclusions: ['Flight tickets', 'Lunch', 'Personal expenses', 'Ayurveda treatments'],
        itinerary: [
            { day: 1, title: 'Cochin Arrival & Fort Kochi', description: 'Arrive in Kochi, explore Fort Kochi, Chinese fishing nets, and Mattancherry Palace.', activities: ['Chinese Fishing Nets', 'Mattancherry Palace', 'Jewish Synagogue', 'Kathakali Show'] },
            { day: 2, title: 'Munnar Tea Gardens', description: 'Drive to Munnar through scenic mountain roads, visit tea estates and Eravikulam National Park.', activities: ['Tea Estate Tour', 'Eravikulam National Park', 'Tea Museum', 'Mattupetty Lake'] },
            { day: 3, title: 'Thekkady Wildlife', description: 'Visit Periyar Tiger Reserve, take a boat safari to spot wildlife.', activities: ['Periyar Boat Safari', 'Spice Garden', 'Elephant Interaction', 'Tribal Village'] },
            { day: 4, title: 'Alleppey Houseboat', description: 'Board a traditional Kerala houseboat, cruise through scenic backwaters.', activities: ['Houseboat Cruise', 'Village Walk', 'Coir Making Demo', 'Sunset on Water'] },
            { day: 5, title: 'Kovalam Beach', description: 'Drive to Kovalam, relax on the crescent-shaped beaches.', activities: ['Lighthouse Beach', 'Hawa Beach', 'Ayurvedic Massage', 'Seafood Dinner'] },
            { day: 6, title: 'Departure', description: 'Morning yoga, then transfer to Trivandrum airport.', activities: ['Morning Yoga', 'Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'c1', name: 'Ayurveda Rejuvenation', price: 3500, duration: '1 day', description: 'Full-day traditional Ayurvedic treatments and massage' },
            { id: 'c2', name: 'Deluxe Houseboat Upgrade', price: 5000, duration: '1 night', description: 'Premium A/C houseboat with private deck and chef' },
            { id: 'c3', name: 'Elephant Safari', price: 2500, duration: '3 hrs', description: 'Elephant ride through jungle at Munnar' },
            { id: 'c4', name: 'Cooking Class', price: 1800, duration: '3 hrs', description: 'Learn to make traditional Kerala cuisine' },
        ],
        faqs: [
            { q: 'Is a houseboat stay included?', a: 'Yes, one night in a standard houseboat is included. Upgrade options available.' },
            { q: 'What is the best route for Kerala trip?', a: 'Cochin → Munnar → Thekkady → Alleppey → Kovalam → Trivandrum is the classic route.' },
        ],
    },
    {
        _id: '4',
        name: 'Rajasthan',
        slug: 'rajasthan',
        state: 'Rajasthan',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1600100595746-8e49b3f6e24a?w=800&q=80',
            'https://images.unsplash.com/photo-1599661046299-2f4d3ec9b7b5?w=800&q=80',
        ],
        shortDescription: 'Land of Kings — royal forts, colorful bazaars, and camel safaris.',
        description: 'Rajasthan is India\'s most royal experience. The state is dotted with magnificent forts and palaces, vibrant desert culture, and bustling bazaars. Experience a royal heritage with warm Rajasthani hospitality.',
        basePrice: 21999,
        duration: 8,
        rating: 4.8,
        reviewCount: 4102,
        isFeatured: true,
        category: 'Heritage',
        difficulty: 'Easy',
        tags: ['Heritage', 'Family', 'Adventure', 'Honeymoon'],
        highlights: ['Jaipur City Tour', 'Udaipur Lake Palace', 'Jaisalmer Safari', 'Jodhpur Blue City', 'Pushkar Festival'],
        bestTimeToVisit: 'October to March',
        weather: { summer: '35-48°C', winter: '10-25°C', monsoon: '28-35°C' },
        inclusions: ['Heritage hotel stay', 'Breakfast & dinner', 'All transfers', 'Camel safari', 'Cultural show'],
        exclusions: ['Flight tickets', 'Lunch', 'Elephant ride Jaipur', 'Personal expenses'],
        itinerary: [
            { day: 1, title: 'Jaipur - Pink City', description: 'Arrive in Jaipur, explore City Palace, Jantar Mantar observatory, and Hawa Mahal.', activities: ['City Palace', 'Jantar Mantar', 'Hawa Mahal', 'Johari Bazar'] },
            { day: 2, title: 'Amber Fort & Surroundings', description: 'Morning visit to Amber Fort, Nahargarh Fort, and Jal Mahal.', activities: ['Amber Fort', 'Nahargarh Fort', 'Jal Mahal', 'Light & Sound Show'] },
            { day: 3, title: 'Jaipur to Jodhpur', description: 'Drive to Jodhpur, explore the Blue City and iconic Mehrangarh Fort.', activities: ['Mehrangarh Fort', 'Sardar Market', 'Blue City Walk', 'Step Well'] },
            { day: 4, title: 'Jodhpur to Jaisalmer', description: 'Drive to Jaisalmer, the Golden City, explore Jaisalmer Fort and Patwon Ki Haveli.', activities: ['Jaisalmer Fort', 'Patwon Ki Haveli', 'Gadsisar Lake', 'Sam Sand Dunes'] },
            { day: 5, title: 'Desert Safari', description: 'Camel safari in Thar Desert, overnight camping in luxury desert camp.', activities: ['Camel Safari', 'Dune Bashing', 'Folk Music & Dance', 'Stargazing'] },
            { day: 6, title: 'Jaisalmer to Udaipur', description: 'Fly/drive to Udaipur, the City of Lakes. Evening boat ride on Lake Pichola.', activities: ['Lake Pichola Boat Ride', 'City Palace View', 'Bagore Ki Haveli'] },
            { day: 7, title: 'Udaipur City Tour', description: 'Visit City Palace, Jagdish Temple, Saheliyon Ki Bari.', activities: ['City Palace Museum', 'Jagdish Temple', 'Sajjangarh Monsoon Palace', 'Vintage Car Museum'] },
            { day: 8, title: 'Departure', description: 'Final morning, transfer to airport. Check out with royal memories.', activities: ['Last Shopping', 'Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'd1', name: 'Hot Air Balloon', price: 8500, duration: '1 hr', description: 'Sunrise hot air balloon over Jaipur/Pushkar' },
            { id: 'd2', name: 'Elephant Ride Amer', price: 2500, duration: '45 min', description: 'Traditional elephant ride to Amber Fort entrance' },
            { id: 'd3', name: 'Royal Dinner Udaipur', price: 4500, duration: '3 hrs', description: 'Dinner on a floating restaurant on Lake Pichola' },
            { id: 'd4', name: 'Desert Camping Upgrade', price: 6000, duration: '1 night', description: 'Luxury Swiss tent with AC and private bathroom in Jaisalmer' },
        ],
        faqs: [
            { q: 'What is the ideal Rajasthan route?', a: 'Jaipur → Jodhpur → Jaisalmer → Udaipur is the Golden Triangle extension.' },
            { q: 'How hot does Rajasthan get in summer?', a: 'Temperature can reach 48°C — avoid May/June. October to March is ideal.' },
        ],
    },
    {
        _id: '5',
        name: 'Manali',
        slug: 'manali',
        state: 'Himachal Pradesh',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1597074866923-dc0589150358?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
            'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&q=80',
        ],
        shortDescription: 'Adventure capital of India — rohtang pass, rivers, and pine forests.',
        description: 'Manali is the ultimate adventure destination in the Indian Himalayas. From the snow-covered Rohtang Pass to the adrenaline rush of river rafting in the Beas River, Manali promises unforgettable experiences.',
        basePrice: 11999,
        duration: 5,
        rating: 4.7,
        reviewCount: 6234,
        isFeatured: true,
        category: 'Adventure',
        difficulty: 'Moderate',
        tags: ['Adventure', 'Mountains', 'Honeymoon', 'Family'],
        highlights: ['Rohtang Pass', 'Solang Valley', 'Hadimba Temple', 'River Rafting', 'Paragliding'],
        bestTimeToVisit: 'October to June',
        weather: { summer: '10-25°C', winter: '-10 to 10°C', monsoon: '15-20°C' },
        inclusions: ['Hotel/resort stay', 'Breakfast', 'Rohtang pass permit', 'All transfers', 'Volvo bus from Delhi'],
        exclusions: ['Flight/train tickets', 'Lunch & dinner', 'Adventure activities', 'Personal expenses'],
        itinerary: [
            { day: 1, title: 'Delhi to Manali (Overnight Journey)', description: 'Board the overnight Volvo bus from Delhi. Arrive in Manali in the morning.', activities: ['Overnight Journey'] },
            { day: 2, title: 'Arrival & Old Manali', description: 'Arrive, freshen up. Explore Old Manali, Hadimba Devi Temple, and nearby waterfalls.', activities: ['Hadimba Temple', 'Old Manali', 'Manu Temple', 'Van Vihar'] },
            { day: 3, title: 'Rohtang Pass Adventure', description: 'Full-day excursion to Rohtang Pass (subject to weather/permit). Snow activities and scenic views.', activities: ['Snow Activities', 'Rohtang Pass Views', 'Solang Valley'] },
            { day: 4, title: 'Adventure Day', description: 'White-water river rafting, paragliding, or Solang Valley winter sports.', activities: ['River Rafting', 'Paragliding', 'Zorbing', 'ATV Ride'] },
            { day: 5, title: 'Departure', description: 'Morning visit to Tibetan market, then board return Volvo to Delhi.', activities: ['Tibetan Market', 'Shopping', 'Departure'] },
        ],
        fitAddOns: [
            { id: 'e1', name: 'Paragliding', price: 2500, duration: '30 min', description: 'Tandem paragliding from Solang Valley with certified pilot' },
            { id: 'e2', name: 'River Rafting', price: 1800, duration: '3 hrs', description: 'Grade 3-4 white water rafting on Beas River' },
            { id: 'e3', name: 'Spiti Valley Extension', price: 12000, duration: '3 days', description: 'Extend trip to remote Spiti Valley monasteries' },
            { id: 'e4', name: 'Snow Bike Ride', price: 2000, duration: '2 hrs', description: 'Ride snowmobiles at Rohtang Pass' },
        ],
        faqs: [
            { q: 'When is Rohtang Pass open?', a: 'May to November usually. It closes in winter due to heavy snowfall.' },
            { q: 'Can I take my car to Manali?', a: 'Yes, NH-3 is well-connected. Drive via Chandigarh for the best experience.' },
        ],
    },
    {
        _id: '6',
        name: 'Andaman Islands',
        slug: 'andaman',
        state: 'Andaman & Nicobar',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80',
            'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&q=80',
        ],
        shortDescription: 'Pristine coral reefs, emerald waters, and untouched island paradise.',
        description: 'The Andaman Islands are India\'s tropical paradise in the Bay of Bengal. With crystal-clear turquoise waters, pristine white-sand beaches, and some of the world\'s best coral reefs, Andaman offers scuba diving, snorkeling, and complete island bliss.',
        basePrice: 24999,
        duration: 6,
        rating: 4.9,
        reviewCount: 2156,
        isFeatured: true,
        category: 'Beach',
        difficulty: 'Easy',
        tags: ['Beach', 'Adventure', 'Honeymoon', 'Family'],
        highlights: ['Havelock Island', 'Radhanagar Beach', 'Scuba Diving', 'Neil Island', 'Cellular Jail'],
        bestTimeToVisit: 'October to May',
        weather: { summer: '27-35°C', winter: '23-30°C', monsoon: '25-30°C' },
        inclusions: ['Resort/hotel stay', 'Daily breakfast', 'Inter-island ferry', 'Airport transfers', 'Cellular Jail Light show'],
        exclusions: ['Flight tickets to Port Blair', 'Lunch & dinner', 'Water sports', 'Personal expenses'],
        itinerary: [
            { day: 1, title: 'Port Blair Arrival', description: 'Arrive Port Blair, visit Cellular Jail and attend evening Light & Sound Show.', activities: ['Cellular Jail Tour', 'Light & Sound Show', 'Port Blair Market'] },
            { day: 2, title: 'Havelock Island', description: 'Ferry to Havelock Island. Visit Asia\'s best beach — Radhanagar Beach (Beach No. 7).', activities: ['Ferry to Havelock', 'Radhanagar Beach', 'Kalapathar Beach'] },
            { day: 3, title: 'Havelock Activities', description: 'Scuba diving or snorkeling at Elephant Beach. Underwater world exploration.', activities: ['Scuba Diving', 'Snorkeling', 'Elephant Beach', 'Sea Walk'] },
            { day: 4, title: 'Neil Island', description: 'Day trip to Neil Island, visit Natural Bridge and Bharatpur Beach.', activities: ['Natural Bridge', 'Bharatpur Beach', 'Laxmanpur Beach'] },
            { day: 5, title: 'Back to Port Blair', description: 'Return ferry, visit Corbyn\'s Cove Beach and Samudrika Naval Museum.', activities: ['Corbyn\'s Cove', 'Naval Museum', 'North Bay Island'] },
            { day: 6, title: 'Departure', description: 'Transfer to Port Blair airport, depart with island memories.', activities: ['Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'f1', name: 'Scuba Diving Certified', price: 5000, duration: '4 hrs', description: 'Open Water Diver certification course (PADI)' },
            { id: 'f2', name: 'Sea Walk', price: 3500, duration: '1 hr', description: 'Walk on the ocean floor in a special helmet' },
            { id: 'f3', name: 'Glass Bottom Boat', price: 1200, duration: '1 hr', description: 'See coral reefs without getting wet' },
            { id: 'f4', name: 'Night Kayaking', price: 2000, duration: '2 hrs', description: 'Bioluminescent plankton kayaking at night' },
        ],
        faqs: [
            { q: 'How do I reach Andaman?', a: 'Direct flights from Delhi, Mumbai, Chennai, and Kolkata to Port Blair. Takes 2-4 hours.' },
            { q: 'Are permits needed?', a: 'No Restricted Area Permit needed for most islands. Some remote areas require permits.' },
        ],
    },
    {
        _id: '7',
        name: 'Varanasi',
        slug: 'varanasi',
        state: 'Uttar Pradesh',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
            'https://images.unsplash.com/photo-1504207815046-f39edc358bd2?w=800&q=80',
        ],
        shortDescription: 'The spiritual capital of India — ancient ghats, Ganga Aarti, and timeless culture.',
        description: 'Varanasi is one of the oldest continuously inhabited cities in the world, and the spiritual capital of India. The city on the banks of the Ganges is a mosaic of life and death, prayer and philosophy. The Ganga Aarti at Dashashwamedha Ghat is a spectacle that touches the soul.',
        basePrice: 9999,
        duration: 4,
        rating: 4.6,
        reviewCount: 3897,
        isFeatured: false,
        category: 'Heritage',
        difficulty: 'Easy',
        tags: ['Heritage', 'Family', 'Adventure'],
        highlights: ['Ganga Aarti', 'Boat Ride at Sunrise', 'Sarnath Buddhist Site', 'Ramnagar Fort', 'BHU Campus'],
        bestTimeToVisit: 'October to March',
        weather: { summer: '35-45°C', winter: '10-20°C', monsoon: '28-33°C' },
        inclusions: ['Hotel stay', 'Breakfast', 'Ganga Aarti tour', 'Sarnath trip', 'Airport transfers'],
        exclusions: ['Flight tickets', 'Lunch & dinner', 'Personal expenses', 'Boat ride'],
        itinerary: [
            { day: 1, title: 'Arrival & Ganga Aarti', description: 'Arrive Varanasi, evening Ganga Aarti at Dashashwamedha Ghat.', activities: ['Ganga Aarti', 'Dashashwamedha Ghat', 'Local Walk'] },
            { day: 2, title: 'Sunrise Boat Ride', description: 'Pre-dawn boat ride on the Ganges to witness sunrise and morning rituals.', activities: ['Sunrise Boat Ride', 'Morning Rituals at Ghats', 'Manikarnika Ghat', 'Old City Walk'] },
            { day: 3, title: 'Sarnath & Temples', description: 'Visit Sarnath — where Buddha gave his first sermon. Tour the Deer Park and Museum.', activities: ['Sarnath Museum', 'Dhamek Stupa', 'Kashi Vishwanath Temple', 'Kal Bhairav Temple'] },
            { day: 4, title: 'Departure', description: 'Morning at leisure, explore local silk market, then transfer to airport.', activities: ['Silk Shopping', 'Street Food Tour', 'Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'g1', name: 'Private Boat Sunrise', price: 2500, duration: '2 hrs', description: 'Private boat for 2 pax at sunrise with photographer' },
            { id: 'g2', name: 'Cooking Class', price: 1800, duration: '3 hrs', description: 'Learn to cook authentic Banarasi cuisine' },
            { id: 'g3', name: 'Yoga & Meditation', price: 1500, duration: 'Morning', description: 'Morning yoga session by the Ganges' },
        ],
        faqs: [
            { q: 'What is the Ganga Aarti timing?', a: 'Evening aarti at 7 PM in winter, 6:30 PM in summer at Dashashwamedha Ghat.' },
            { q: 'Is Varanasi suitable for families?', a: 'Yes, though the surroundings can be intense. It is deeply enriching for all ages.' },
        ],
    },
    {
        _id: '8',
        name: 'Leh Ladakh',
        slug: 'ladakh',
        state: 'Ladakh',
        country: 'India',
        heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
        gallery: [
            'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&q=80',
            'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&q=80',
        ],
        shortDescription: 'The land of high passes — Pangong Lake, monasteries, and starry skies.',
        description: 'Ladakh is one of the most extraordinary destinations in the world. At an average elevation of 3,500 meters, the "Land of High Passes" offers stark, dramatic landscapes, ancient Buddhist monasteries, the iconic Pangong Lake, and an unmatched sense of isolation and peace.',
        basePrice: 29999,
        duration: 9,
        rating: 4.9,
        reviewCount: 1987,
        isFeatured: true,
        category: 'Adventure',
        difficulty: 'Challenging',
        tags: ['Adventure', 'Mountains', 'Family'],
        highlights: ['Pangong Lake', 'Nubra Valley', 'Khardung La Pass', 'Diskit Monastery', 'Leh Palace'],
        bestTimeToVisit: 'May to September',
        weather: { summer: '10-25°C', winter: '-30 to -10°C', monsoon: '12-22°C' },
        inclusions: ['Guesthouse/hotel stay', 'Breakfast & dinner', 'All permits', 'Airport transfers', 'Nubra Valley camp'],
        exclusions: ['Flight tickets', 'Lunch', 'Personal expenses', 'Mountain bikes'],
        itinerary: [
            { day: 1, title: 'Arrive Leh - Acclimatize', description: 'Arrive in Leh (3500m). Full day rest for acclimatization. Light walk to local market.', activities: ['Leh Market Walk', 'Leh Palace View', 'Rest & Acclimatization'] },
            { day: 2, title: 'Leh City Tour', description: 'Visit Leh Palace, Shanti Stupa, and Thiksey Monastery.', activities: ['Leh Palace', 'Shanti Stupa', 'Thiksey Monastery', 'Hall of Fame'] },
            { day: 3, title: 'Nubra Valley via Khardung La', description: 'Drive over Khardung La — world\'s highest motorable road. Arrive Nubra Valley.', activities: ['Khardung La Pass (5359m)', 'Bactrian Camel Ride', 'Diskit Monastery'] },
            { day: 4, title: 'Nubra Valley Exploration', description: 'Explore Hunder sand dunes, white sand beaches, visit Samstanling Monastery.', activities: ['Hunder Sand Dunes', 'Sumur Monastery', 'Local Village Walk'] },
            { day: 5, title: 'Pangong Lake', description: 'Drive to iconic Pangong Lake (4350m). The lake is famous for changing colors.', activities: ['Pangong Lake Views', 'Stargazing', 'Photography'] },
            { day: 6, title: 'Pangong to Leh', description: 'Return to Leh via Changla Pass. Visit Hemis Monastery en route.', activities: ['Changla Pass', 'Hemis Monastery', 'Shey Palace'] },
            { day: 7, title: 'Magnetic Hill & Gurudwara', description: 'Visit Magnetic Hill, Sangam where Indus and Zanskar rivers meet, and Pathar Sahib Gurudwara.', activities: ['Magnetic Hill', 'Sangam Confluence', 'Pathar Sahib', 'Gurudwara'] },
            { day: 8, title: 'Free Day / Optional Activities', description: 'Optional mountain biking, trekking, or relaxation.', activities: ['Mountain Biking', 'Local Market', 'Yoga'] },
            { day: 9, title: 'Departure', description: 'Early morning transfer to Leh Airport for departure.', activities: ['Airport Transfer'] },
        ],
        fitAddOns: [
            { id: 'h1', name: 'Mountain Biking Tour', price: 4500, duration: '1 day', description: 'Guided mountain bike ride through scenic Ladakhi terrain' },
            { id: 'h2', name: 'White Water Rafting Zanskar', price: 5500, duration: 'Full day', description: 'Grade 4 rafting on the Zanskar River gorge' },
            { id: 'h3', name: 'Trekking Package', price: 8000, duration: '3 days', description: 'Markha Valley trek with camping' },
            { id: 'h4', name: 'Stargazing Night', price: 3000, duration: 'Night', description: 'Telescope-guided stargazing at Pangong Lake (darkest skies in India)' },
        ],
        faqs: [
            { q: 'How to deal with altitude sickness in Ladakh?', a: 'Stay hydrated, avoid alcohol, rest well on day 1. Consult doctor before travel if you have health concerns.' },
            { q: 'Is Ladakh accessible by road?', a: 'Yes, via Manali-Leh Highway (June-Oct) or Srinagar-Leh Highway (May-Nov). Flights to Leh year-round.' },
        ],
    },
];

export const MOCK_PACKAGES = [
    { _id: 'p1', name: 'Kashmir Honeymoon Delight', destinationId: '1', slug: 'kashmir-honeymoon', price: 32999, duration: 7, category: 'Honeymoon', rating: 4.9 },
    { _id: 'p2', name: 'Kerala Backwaters Escape', destinationId: '3', slug: 'kerala-backwaters', price: 22999, duration: 6, category: 'Relaxation', rating: 4.8 },
    { _id: 'p3', name: 'Rajasthan Royal Heritage', destinationId: '4', slug: 'rajasthan-royal', price: 35999, duration: 8, category: 'Heritage', rating: 4.9 },
    { _id: 'p4', name: 'Ladakh Adventure Circuit', destinationId: '8', slug: 'ladakh-adventure', price: 45999, duration: 9, category: 'Adventure', rating: 4.9 },
];

export const MOCK_TESTIMONIALS = [
    {
        _id: 't1',
        name: 'Priya Sharma',
        city: 'Delhi',
        destination: 'Kashmir',
        rating: 5,
        text: 'The most magical trip of my life! GoTravel organized everything flawlessly. The houseboat on Dal Lake was beyond our expectations. Highly recommend the Kashmir package!',
        avatar: 'https://i.pravatar.cc/100?img=1',
        date: '2024-01-15',
    },
    {
        _id: 't2',
        name: 'Rahul Mehta',
        city: 'Mumbai',
        destination: 'Kerala',
        rating: 5,
        text: 'The Kerala backwaters experience was surreal. Our houseboat had everything — delicious food, beautiful views, incredible sunsets. 10/10 would book again.',
        avatar: 'https://i.pravatar.cc/100?img=3',
        date: '2024-02-08',
    },
    {
        _id: 't3',
        name: 'Anjali Singh',
        city: 'Bangalore',
        destination: 'Goa',
        rating: 5,
        text: 'Perfect anniversary trip! The hotel was beachside, food was amazing, and GoTravel\'s team was available 24/7. Already planning our next trip through them.',
        avatar: 'https://i.pravatar.cc/100?img=5',
        date: '2024-01-28',
    },
    {
        _id: 't4',
        name: 'Vikram Nair',
        city: 'Chennai',
        destination: 'Ladakh',
        rating: 5,
        text: 'GoTravel made Ladakh completely hassle-free! All permits, accommodation, and transfers were sorted. Pangong Lake at sunrise is something I\'ll never forget.',
        avatar: 'https://i.pravatar.cc/100?img=7',
        date: '2024-03-12',
    },
    {
        _id: 't5',
        name: 'Sneha Patel',
        city: 'Ahmedabad',
        destination: 'Rajasthan',
        rating: 5,
        text: 'The Rajasthan trip was a royal experience! We stayed in heritage havelis, rode camels in the Thar desert, and the sunset at Udaipur was breathtaking.',
        avatar: 'https://i.pravatar.cc/100?img=9',
        date: '2024-02-20',
    },
    {
        _id: 't6',
        name: 'Arjun Khanna',
        city: 'Pune',
        destination: 'Andaman',
        rating: 5,
        text: 'Andaman exceeded all expectations. Crystal clear water, white sand, amazing coral reefs. GoTravel handled everything perfectly. Literally paradise!',
        avatar: 'https://i.pravatar.cc/100?img=11',
        date: '2024-03-05',
    },
];

export function getDestinationBySlug(slug: string) {
    return MOCK_DESTINATIONS.find(d => d.slug === slug) || null;
}

export function getFeaturedDestinations() {
    return MOCK_DESTINATIONS.filter(d => d.isFeatured);
}

export function searchDestinations(query: string, tags: string[] = []) {
    return MOCK_DESTINATIONS.filter(d => {
        const matchesQuery = !query || d.name.toLowerCase().includes(query.toLowerCase()) || d.state.toLowerCase().includes(query.toLowerCase());
        const matchesTags = tags.length === 0 || tags.some(t => d.tags.includes(t));
        return matchesQuery && matchesTags;
    });
}
